version: '3'
services:
  backend_izi_bot:
    image: alwaly/backend_izi_bot
    ports:
      - "8081:8081"
    networks:
      - api_network
    depends_on:
      - mongo_database
      - qdrant

  mongo_database:
    image: mongo:5.0.22
    ports:
      - "27017:27017"
    networks:
      - api_network
    volumes:
      - ./data:/data/db

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    networks:
      - api_network

networks:
  api_network: 
    driver: bridge
